server:
  port: 7080

spring:
  application:
    name: microsrv-provider-user-v1 #使用版本号v1

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.hostname}:${spring.cloud.client.ipAddress}:${spring.application.name}:${spring.application.instance_id:${server.port}}
