server:
  port: 7070

spring:
  application:
    name: microsrv-consumer-register-withHystrix
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}